/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import Clases.CConexion;
import Clases.Cliente;
import Clases.ClienteDAO;
import GUI.Tablas.tablaGenérica;
import GUI.Tablas.tableDesigner;

/**
 *
 * @author FrancisR
 */
public class ClientesMenu extends javax.swing.JPanel {
 
    /**
     * Creates new form ClientesMenu
     */
    
    CConexion conexion = CConexion.getInstance();
    ClienteDAO cliente = new ClienteDAO(conexion.getConexion());
    
    
    public ClientesMenu() {
        initComponents();
        tableDesigner td = new tableDesigner();
        td.designTable(tblCliente,jScrollPane2);        
        actualizar();
    }
    
    private void actualizar(){
        tablaGenérica<Cliente> tablaCliente = new tablaGenérica<>();
        String[] columnas = {"ID", "Nombre", "Dirección", "Email", "Telefono","Credito"};
        tablaCliente.actualizarTabla(cliente.obtenerListaClientes(), columnas, tblCliente);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jPanel18.setBackground(new java.awt.Color(242, 242, 242));

        jPanel19.setBackground(new java.awt.Color(242, 242, 242));
        jPanel18.add(jPanel19);

        jPanel20.setBackground(new java.awt.Color(242, 242, 242));
        jPanel18.add(jPanel20);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jScrollPane2.setToolTipText("");

        tblCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCliente.setRowHeight(40);
        tblCliente.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tblCliente.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(tblCliente);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 740, 560));

        jPanel5.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, 190, 110));

        jPanel12.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 550, 190, 110));

        jPanel15.setBackground(new java.awt.Color(242, 242, 242));

        jPanel16.setBackground(new java.awt.Color(242, 242, 242));
        jPanel15.add(jPanel16);

        jPanel17.setBackground(new java.awt.Color(242, 242, 242));
        jPanel15.add(jPanel17);

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 100, 190, 110));

        jPanel21.setBackground(new java.awt.Color(242, 242, 242));

        jPanel22.setBackground(new java.awt.Color(242, 242, 242));
        jPanel21.add(jPanel22);

        jPanel23.setBackground(new java.awt.Color(242, 242, 242));
        jPanel21.add(jPanel23);

        jPanel1.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 190, 110));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(60, 63, 65));
        jLabel1.setText("Clientes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/usuario.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 40, 40));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblCliente;
    // End of variables declaration//GEN-END:variables
}
