/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import GUI.Clientes.ClientesMenu;
import Clases.CConexion;
import java.awt.Color;

/**
 *
 * @author FrancisR
 */
public class Principal extends javax.swing.JFrame {
    private static Principal instance;

    /**
     * Creates new form Principal
     */
    
    private Principal() {
        CConexion conexion = CConexion.getInstance();
        initComponents();
    }
    
    
    //Obtener instancia de menu principal
    public static synchronized Principal getInstance() {
        if (instance == null) {
            instance = new Principal();
        }
        return instance;
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        MenuBar = new javax.swing.JPanel();
        Cajas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Clientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Consulta = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Facturas = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PanelDinamico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1200, 700));

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MenuBar.setBackground(new java.awt.Color(54, 54, 54));
        MenuBar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cajas.setBackground(new java.awt.Color(54, 54, 54));
        Cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CajasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CajasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CajasMouseExited(evt);
            }
        });
        Cajas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cajas");
        Cajas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 60, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/caja-fuerte.png"))); // NOI18N
        Cajas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        MenuBar.add(Cajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 190, 60));

        Clientes.setBackground(new java.awt.Color(54, 54, 54));
        Clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClientesMouseExited(evt);
            }
        });
        Clientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Clientes");
        Clientes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        Clientes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        MenuBar.add(Clientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 190, 60));

        Consulta.setBackground(new java.awt.Color(54, 54, 54));
        Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConsultaMouseExited(evt);
            }
        });
        Consulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Consulta");
        Consulta.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/base-de-datos.png"))); // NOI18N
        jLabel6.setText("jLabel3");
        Consulta.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        MenuBar.add(Consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 190, 60));

        Facturas.setBackground(new java.awt.Color(54, 54, 54));
        Facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FacturasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FacturasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FacturasMouseExited(evt);
            }
        });
        Facturas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Facturas");
        Facturas.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/factura.png"))); // NOI18N
        Facturas.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        MenuBar.add(Facturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 190, 60));

        Fondo.add(MenuBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        PanelDinamico.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDinamicoLayout = new javax.swing.GroupLayout(PanelDinamico);
        PanelDinamico.setLayout(PanelDinamicoLayout);
        PanelDinamicoLayout.setHorizontalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        PanelDinamicoLayout.setVerticalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        Fondo.add(PanelDinamico, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 0, 1020, 706));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseEntered
        Clientes.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_ClientesMouseEntered

    private void ClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseExited
        Clientes.setBackground(new Color(54,54,54));
    }//GEN-LAST:event_ClientesMouseExited

    private void FacturasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturasMouseEntered
        Facturas.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_FacturasMouseEntered

    private void FacturasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturasMouseExited
        Facturas.setBackground(new Color(54,54,54));
    }//GEN-LAST:event_FacturasMouseExited

    private void CajasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajasMouseEntered
        Cajas.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_CajasMouseEntered

    private void CajasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajasMouseExited
        Cajas.setBackground(new Color(54,54,54));
    }//GEN-LAST:event_CajasMouseExited

    private void ConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseExited
        Consulta.setBackground(new Color(54,54,54));
    }//GEN-LAST:event_ConsultaMouseExited

    private void ConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseEntered
        Consulta.setBackground(new Color(33,33,33));
    }//GEN-LAST:event_ConsultaMouseEntered

    private void ClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientesMouseClicked
        ClientesMenu cm = new ClientesMenu();
        cm.setSize(1020, 700);
        cm.setLocation(0, 0);
        PanelDinamico.removeAll();
        PanelDinamico.add(cm);
        revalidate();
        repaint();
    }//GEN-LAST:event_ClientesMouseClicked

    private void FacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FacturasMouseClicked
        FacturaMenu fm = new FacturaMenu();
        fm.setSize(1020, 700);
        fm.setLocation(0, 0);
        PanelDinamico.removeAll();
        PanelDinamico.add(fm);
        revalidate();
        repaint();
    }//GEN-LAST:event_FacturasMouseClicked

    private void CajasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajasMouseClicked
        CajaBancoMenu cb = new CajaBancoMenu();
        cb.setSize(1020, 700);
        cb.setLocation(0, 0);
        PanelDinamico.removeAll();
        PanelDinamico.add(cb);
        revalidate();
        repaint();
    }//GEN-LAST:event_CajasMouseClicked

    private void ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultaMouseClicked
        ConsultasMenu ct = new ConsultasMenu();
        ct.setSize(1020, 700);
        ct.setLocation(0, 0);
        PanelDinamico.removeAll();
        PanelDinamico.add(ct);
        revalidate();
        repaint();
    }//GEN-LAST:event_ConsultaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cajas;
    private javax.swing.JPanel Clientes;
    private javax.swing.JPanel Consulta;
    private javax.swing.JPanel Facturas;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JPanel PanelDinamico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
